# Configuration file for Saguaro plugin

# enable telnet server
telnet-enabled: true

# telnet server listening port
telnet-port: 25550

# enable file output
file-output-enabled: false

# file update period (in seconds)
file-update-period: 60

# TPS sample period (in seconds)
tps-sample-period: 60

